version: '3.8'

services:
  mainnet:
    build: .
    restart: always
    volumes:
      - ".:/work"
    ports:
      - "9000:9000"
    command: "json-caching-proxy --config mainnet-config.json"

  testnet:
    build: .
    restart: always
    volumes:
      - ".:/work"
    ports:
      - "9001:9001"
    command: "json-caching-proxy --config testnet-config.json"

  mainnet-backup:
    image: jsonfry/curl-cron:latest
    restart: always
    volumes:
      - ".:/work"
    environment:
      - OPTIONS=mainnet:9000/proxy/har --output /work/mainnet.har
      - CRON_SCHEDULE=0 * * * *

  testnet-backup:
    image: jsonfry/curl-cron:latest
    restart: always
    volumes:
      - ".:/work"
    environment:
      - OPTIONS=testnet:9001/proxy/har --output /work/testnet.har
      - CRON_SCHEDULE=0 * * * *
